# Experiments

In [2]:
import pandas as pd

## DF erstellen

In [5]:
pd.DataFrame([
    {"a": 1, "b": 2},
    {"a": 2, "b": 4},
    {"a": 3, "b": 6},
])

   a  b
0  1  2
1  2  4
2  3  6

In [6]:
pd.DataFrame({
    "a": [1, 2, 3],
    "b": [2, 4, 6],
})

   a  b
0  1  2
1  2  4
2  3  6